name: build-site

on:
  schedule:
    - cron: '0 8 * * SUN'   # Domingo 10:00 Madrid aprox. en verano (CEST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        run: python build.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data docs/index.html docs/archivo.html docs/styles.css docs/app.js
          git commit -m "chore: auto-build edition $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
