name: Fix NLTK + Rebuild

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Asegurar dependencias
      - name: Patch requirements.txt (add nltk)
        run: |
          if [ ! -f requirements.txt ]; then
            echo "feedparser==6.0.11" > requirements.txt
            echo "beautifulsoup4==4.12.3" >> requirements.txt
            echo "requests==2.32.3" >> requirements.txt
            echo "lxml==5.2.2" >> requirements.txt
            echo "sumy==0.11.0" >> requirements.txt
          fi
          grep -qi '^nltk' requirements.txt || echo "nltk==3.8.1" >> requirements.txt

      # 2) Inyectar guard en build.py para descargar punkt/punkt_tab si falta
      - name: Patch build.py (ensure NLTK data)
        run: |
          python - <<'PY'
          import io,sys,os,re
          p = "build.py"
          src = open(p, encoding="utf-8").read()
          if "def _ensure_nltk_data()" not in src:
              guard = '''
          def _ensure_nltk_data():
              try:
                  import nltk
                  try:
                      nltk.data.find('tokenizers/punkt')
                  except LookupError:
                      nltk.download('punkt', quiet=True)
                  # desde NLTK 3.8 separaron punkt_tab
                  try:
                      nltk.data.find('tokenizers/punkt_tab')
                  except LookupError:
                      try:
                          nltk.download('punkt_tab', quiet=True)
                      except Exception:
                          pass
              except Exception:
                  pass
          '''
              # incrusta el guard y llámalo al inicio de main()
              src = src.replace("def main():", guard + "\n\ndef main():\n    _ensure_nltk_data()\n", 1)
              open(p, "w", encoding="utf-8").write(src)
          PY

      # 3) Instalar deps y descargar datos NLTK en el runner
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data (punkt & punkt_tab)
        run: |
          python - <<'PY'
          import nltk
          nltk.download('punkt', quiet=True)
          try:
              nltk.download('punkt_tab', quiet=True)
          except Exception as e:
              print("punt_tab no disponible, continuo:", e)
          PY

      # 4) Ejecutar el generador para que ya haya contenido hoy
      - name: Build now
        run: |
          python build.py

      # 5) Commit & push
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt build.py docs/data
          git commit -m "fix(nltk): add nltk + download punkt data; rebuild edition" || echo "Sin cambios"
          git push
